### ISSUE TITLE
Probleme mit Tabellen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/design-rrze#1]
Bei eingeschalteten Sidebars (3 spaltiges Deisgn) werrden Tabellen, die in der Mitte sind, rechts abgeschnitten.

Ggf hier entweder ein scrolling einbauen oder/und die Sidebar rechts etwas verkelinern (auch in der Schriftgröße ggf. 0.9 em drauf?)

**Comment by rvdforst** [comment]
Bug wurde behoben. Siehe https://github.com/RRZE-Webteam/Design-RRZE/commit/f0ca753edbcbd4655e6e8eb463f16f5640baa3a5

**Comment by xwolfde** [comment]
Hm, das hat den Content overflowable gemacht, nicht nur die Table um die es geht. Das kann man noch besser lösen. Ich schau mal bei Gelegenheit.

**Comment by xwolfde** [comment]
Ausserdem muss ein Scrollbalken sichtbar werden, wenn es notwendig wird.

**Comment by xwolfde** [comment]
Druck-CSS muss auch noch gecheckt werden.
