### ISSUE TITLE
ym-table und mehrzeilige Spaltenangaben

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/design-rrze#3]
Shortcode ym-table kommt nicht mit mehrzeiligen Inhaltsfelder klar obwohl der Delemiter richtig gesetzt ist. Beispiel:

[ym-table class="bordertable" delimiter=";"]
Adresse;<span class="org">Universität Augsburg</span>
<span class="organization-unit">Rechenzentrum</span>
<span class="street-address">Universitätsstraße 8</span>
<span class="postal-code">86159</span> <span class="locality">Augsburg</span>
Telefon;0821 / 598-2000
Fax;0821 / 598-2028
Offizielle Webadresse;http://www.rz.uni-augsburg.de
[/ym-table]

**Comment by endv02** [comment]
Zeilenumbruch durch Eingabe von :br: möglich, siehe https://github.com/RRZE-Webteam/design-rrze/commit/060701b43b2de750787bb02ac391ea0fc41d3881
