### ISSUE TITLE
Klick auf Titel (oben in Bühne) auf Unterseiten nicht möglich

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/design-rrze#4]
Auf Unterseiten muss man auf den Titel klicken können um zur definierten Startseite (home_url()) zurück zu kommen.

**Comment by endv02** [comment]
Ergänzt, siehe https://github.com/RRZE-Webteam/design-rrze/commit/8d804359b94884af42d92ff0efb9aff738c95088
